services:
  database-ug:
    container_name: database-ug
    image: postgres:16.4-alpine3.20
    restart: always
    ports: 
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=games_usability
    volumes:
      - database-ug-data-dev:/var/lib/postgresql/data # Volumen para persistir los datos
    networks:
      - my-network

  backend-ug:
    container_name: backend-ug
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - venv-dependencies:/app/.venv
    networks:
      - my-network
    command: [ "/app/.venv/bin/uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "${PORT}" ]

volumes:
  database-ug-data-dev:
  venv-dependencies:


networks:
  my-network:
    driver: bridge
